### ISSUE TITLE
Pretraining Model

### ISSUE THREAD

**Issue by AKaganKaya** [Yibin-Lei/ReContriever#1]
Thank you so much your great work. Can you share pretraining model?

**Comment by Yibin-Lei** [comment]
Hi @AKaganKaya,

Thank you for your kind words! The pretrained models have been released. Please feel free to ask any further questions.

Best,
Yibin

**Comment by Yibin-Lei** [comment]
Close the issue as no further action is required. Please feel free to reopen it if needed.
